# Pre-commit hooks configuration for Daily Alert Summary Agent
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Black code formatter - pinned to exact version as specified
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Exact version pin as required by task
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=100, --target-version=py310]

  # isort import sorter - pinned to exact version as specified
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Exact version pin as required by task
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # mypy type checker - pinned to exact version as specified
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # Exact version pin as required by task (mirrors mypy 1.10.0)
    hooks:
      - id: mypy
        additional_dependencies: [
          types-requests,
          types-PyYAML,
          types-click,
          pydantic,
          pydantic-settings,
          httpx,
          loguru,
          rich,
        ]
        args: [--python-version=3.10, --disable-error-code=call-arg, --disable-error-code=unused-ignore]
        files: ^src/

  # Check for Python security issues
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [--recursive]
        files: ^src/

default_language_version:
  python: python3.10
